name: Ejecutar tests Robot Framework simples

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Robot Framework and SeleniumLibrary
      run: pip install robotframework selenium robotframework-seleniumlibrary

    - name: Run tests
      run: robot testsuite/
