name: Run WebDriverIO Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  webdriverio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Run WebDriverIO tests
        run: |
          npx wdio run wdio.conf.js

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: wdio-html-report
          path: ./reports/html-reports
